# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['PGHOST'] %>
  username: <%= ENV['PGUSER'] %>
  password: <%= ENV['PGPASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['PGDBNAME'] %>-development

test:
  adapter: sqlite3
  database: ":memory:"
  verbosity: quiet

production:
  adapter: postgresql
  username: "produciton_rds"
  password: "password"
  host: "produciton.c3ssrcrj9xkk.us-east-1.rds.amazonaws.com"
  database: "produciton_production"
